### ISSUE TITLE
tinymce-error with protect.js

### ISSUE THREAD

**Issue by awello** [plone/plone4.csrffixes#2]
In line 29 there is no check, if send is patched yet - using an overlay is overwriting the _send-function with the patched send-function and so my browser is running in endless recursion.

My solution was: patching the send-function only if _send is undefined ...

(plone 4.1)

**Comment by cekk** [comment]
I can confirm this issue also for Plone 4.2 (in general for all tiny < 1.3.x)

**Comment by vangheem** [comment]
Fixed here: https://github.com/plone/plone4.csrffixes/commit/9b9c067af33246de1bd266b1458aba2ec45bda06
