### ISSUE TITLE
Update the version of the plone.protect in documentation

### ISSUE THREAD

**Issue by idgserpro** [plone/plone4.csrffixes#23]
After [this commit](https://github.com/plone/plone4.csrffixes/commit/e5d9852bc9fc3c924a8b8cd147a6877fa6841e86), the version of ```plone.protect``` should be updated in the [documentation](https://github.com/plone/plone4.csrffixes/blob/master/README.rst#plone-43-42-41-and-40) for 3.0.19.

**Comment by mauritsvanrees** [comment]
True. I have updated the readme and have manually changed the text on PyPI. I also updated plone.locking to the latest 2.0.9.
Thanks for keeping an eye on this and reporting it!
