### ISSUE TITLE
Problems with Archetypes calendarwidget

### ISSUE THREAD

**Issue by jensens** [plone/plone4.csrffixes#4]
see PR at plone/Products.Archetypes#50

**Comment by vangheem** [comment]
This must be an lxml caveat. Does anyone know lxml well enough on how to prevent it from doing this along with auto encoding html entities? We like the dom manipulation but don't like the auto encoding going on...

**Comment by vangheem** [comment]
It looks like changing the serializer to always be lxml.html.tostring in plone.protect's parseTree method fixes this issue.

**Comment by vangheem** [comment]
https://github.com/plone/plone.protect/commit/21c12b66f94bb57e63f0094da8e4750dc104c13a fixes this issue.
